# Generated by Django 3.2.4 on 2022-03-26 17:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('marka', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=200, null=True)),
                ('mileage', models.CharField(blank=True, max_length=200, null=True)),
                ('car_image', models.ImageField(upload_to='media')),
                ('condition', models.CharField(blank=True, max_length=200, null=True)),
                ('brend', models.CharField(max_length=100)),
                ('dealer_comments', models.CharField(max_length=300)),
                ('kilometres', models.CharField(max_length=60)),
                ('colour', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('drive_type', models.CharField(max_length=100)),
                ('in_depth_specifications', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
