# Generated by Django 3.2.4 on 2022-03-26 19:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='marka',
        ),
        migrations.AlterField(
            model_name='offers',
            name='in_depth_specifications',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
