# Generated by Django 3.2.4 on 2022-03-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220326_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='condition_category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='conditioncategory',
            name='category',
        ),
        migrations.AddField(
            model_name='conditioncategory',
            name='name',
            field=models.CharField(db_index=True, default='sdad', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conditioncategory',
            name='slug',
            field=models.SlugField(default='sdsdsd', unique=True),
            preserve_default=False,
        ),
    ]
