# Generated by Django 3.2.4 on 2022-03-29 09:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_address_working_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='in_depth_specifications',
            new_name='in_depth_specifications1',
        ),
        migrations.AddField(
            model_name='car',
            name='in_depth_specifications2',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='sadasds'),
            preserve_default=False,
        ),
    ]
