# Generated by Django 3.2.4 on 2022-03-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220329_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_category',
        ),
    ]
