# Generated by Django 3.2.4 on 2022-03-31 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_carcategory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_category',
            new_name='categories',
        ),
    ]
