# Generated by Django 3.2.4 on 2022-03-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_car_category_car_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcategory',
            name='slug',
            field=models.SlugField(default='toyota', unique=True),
            preserve_default=False,
        ),
    ]
